name: Metrics
on:
  # Schedule updates (every 24 hours)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["main", "master"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Step 1: Generate isocalendar only (for 3D calendar)
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: jvisualschool
          template: classic
          base: ""
          config_timezone: Asia/Seoul
          filename: isocalendar.svg
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
